elastic/ems-client

.gitignore

Ignore intellij

---

package.json

Bump to 1.0.2

---

package.json

Syncs up next version with npm (which already had a 1.0.2)

bump to 1.0.3

---

.eslintrc
.prettierrc
package.json
src/ems_client.ts
src/ems_service.ts
src/file_layer.ts
yarn.lock

I found some additional linting problems when I added prettier. This should help us maintain better code quality.
This also adds a pre-commit hook to run tests and lint to avoid committing bad code (something I have been guilty of).

Add prettier for better linting

---

.eslintrc
.prettierrc
package.json
src/ems_client.ts
src/ems_service.ts
src/file_layer.ts
yarn.lock

- Add prettier for better linting (#28)

[7.x] Add prettier for better linting (#28)

---

src/file_layer.ts
src/index.ts
test/ems_client.test.ts

- Export FileLayer and TMSService (#35)

[7.x] Export FileLayer and TMSService (#35)

---

src/file_layer.ts
src/index.ts
test/ems_client.test.ts

Backports the following commits to 7.9:
- Export FileLayer and TMSService (#35)

[7.9] Export FileLayer and TMSService (#35)

---

src/ems_client.ts
src/file_layer.ts
test/ems_client.test.ts
test/ems_mocks/sample_files.json
test/ems_mocks/sample_files_proxied.json

Backports the following commits to 7.10:
- Add functions to get specific file formats (#53)

[7.10] Add functions to get specific file formats (#53)

---

CHANGELOG.md
package.json
src/ems_client.ts
yarn.lock

Sets the default EMS version to 7.12. No substantial changes.

Bump to EMS 7.12

---

CHANGELOG.md
package.json
src/ems_client.ts

Part of elastic/ems-file-service#220
Following instructions in `CONTRIBUTING.md`, updated assets to `7.14.0`.

Release 7.14.0

---

src/index.ts

Closes https://github.com/elastic/ems-client/issues/71

[Maps] Export FileLayerField

---

package.json
yarn.lock

Fixes #76 
Set a range for `semver` dependency.

Put range on semver dependency

---

src/index.ts
src/tms_service.ts

Export EmsSprite and EmsSpritesheet types

---

package.json
src/tms_service.ts
test/ems_client.test.ts
yarn.lock

Inherit types from maplibre-gl

---

src/tms_service.ts

Add `sdf` property to EmsSprite type

---

.backportrc.json
CHANGELOG.md
package.json
src/ems_client.ts

Bump to 8.2.0

---

.backportrc.json
CHANGELOG.md
package.json
src/ems_client.ts

Bump resources in `master` to `8.3`.

Bump master to 8.3

---

CHANGELOG.md

Updates the CHANGELOG to publish 8.3.0

Release 8.3.0

---

CHANGELOG.md
package.json

Fixes changelog from #106 and updates `package.json` to `8.3.1`

Release 8.3.1

---

.backportrc.json

This is an automatic backport of pull request #108 to 8.3.
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) for additional information

[8.3] Update backport config to 8.3 (#108)

---

CHANGELOG.md
package.json

This is an automatic backport of pull request #113 to 8.3.
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) for additional information

[8.3] Release 8.3.2 (#113)

---

src/tms_service.ts

Make percentage an optional parameter

---

CHANGELOG.md
package.json

Releases the third iteration of the `ems-client` for the `8.3` Elastic stack.

Release 8.3.3

---

CHANGELOG.md
package.json

This is an automatic backport of pull request #120 to 8.3.
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) for additional information

[8.3] Release 8.3.3 (#120)

---

package.json

Bumps `master` branch to `8.4.0` to follow the practice on the rest of the Stack

Bump master branch to 8.4.0

---

package.json

Bumping to 7.17.1 in case we need to release a patch version

Bump to 7.17.1

---

package.json

Bumping this branch to set it up in case we need to update the client for Kibana/Landing Page versions that depend from 8.3

Bump to 8.3.4

---

CHANGELOG.md
CONTRIBUTING.md

Brief description of how CI works on this repository.

Add CI docs

---

package.json
yarn.lock

Upgrades `semver` to `7.5.2` and its types to the latest version `7.5.0`.

Upgrade semver

---

CHANGELOG.md

Part of  elastic/kibana#157094
* Updates the CHANGELOG for 8.5.0 release
```[tasklist]
```

Release EMS Client 8.5.0

---

CHANGELOG.md

Update CHANGELOG to prepare 8.4.1 for release.

Release 8.4.1

---

CHANGELOG.md
package.json
yarn.lock

Upgrade:
- babel
- lodash and node types
- typescript-eslint
- eslint
- globals
- prettier
- ts-jest

Upgrade dependencies

---

CHANGELOG.md

Update the `CHANGELOG.md` with references to the closed PRs, all regarding dependencies updates.

[7.17] Update CHANGELOG

---

src/tms_service.ts

Related to https://github.com/elastic/kibana/issues/201269
Adding coloring options for the three new styles being added to EMS so consumers of the library now how to modify the basemap styles.
> [!important]
> With this PR we will do the `8.5.4` release of the library, to be consumed by Kibana and EMS Landing Page (9 and 8 branches).

Add color processors for upcoming new styles

---

CHANGELOG.md

Updates the CHANGELOG to get ready to release a new update for 7.17
Only dependencies updates for this release.

7.17.4 changelog

---

CHANGELOG.md
package.json

Reverts elastic/ems-client#498

Revert "Bump to 7.17.5"

---

CHANGELOG.md

Updates CHANGELOG to release `8.6.2`.

[skip-ci] Update CHANGELOG

---

CHANGELOG.md

Update the CHANGELOG to release `v8.6.3`

Release 8.6.3

---

CHANGELOG.md
yarn.lock

Fixes `yarn.lock` and updates `CHANGELOG.md` to make this branch ready for release.

Release 7.17.6

---

.buildkite/pipeline.yml

Updates our CI image to the latest definition.

[ci] Update CI image
