elastic/ems-client

- package.json
It was pointing to an incorrect path, which fell back to the main entry
> Updates browser entry point

- babel.config.js
While trying to add CI I noticed that tests are currently failing because [Jest sets the `process.env.NODE_ENV` to `test`](https://jestjs.io/docs/en/getting-started#using-babel) which we do not have in babel config. This PR adds an `env` for test.
> Add babel env for jest

- src/tms_service.js
This fixes the handling of vector tile sources from EMS by injecting the attributions from the root manifest.
> Inject correct attribution into vector tile sources

- src/tms_service.js
- test/ems_client.test.js
Wrapping the attributions in a `<p>` element may cause newlines to appear in some clients. So let's remove that.
> Remove paragraph element from html attribution

- README.md
- src/ems_client.js
- test/ems_client.test.js
- test/ems_client_util.js
Fixes #17. 
This PR adds an `appName` parameter to the constructor which updates the `my_app_name` parameter in the query string in requests to EMS. Previously, `my_app_name` was hardcoded to "kibana", but we should support additional clients such as ems-landing-page. `appName` defaults to "kibana" if not specified.
This PR also adds a `appVersion` parameter designed to replace the `kbnVersion` parameter in the constructor since `kbnVersion` is a bit of a misnomer since ems-client supports additional clients besides Kibana. A deprecation warning is logged if `kbnVersion` is specified. Both `appVersion` and `kbnVersion` apply the `my_app_version` query string parameter in requests to EMS. If not specified, `appVersion` falls back to the `kbnVersion` parameter.
> Add appName and appVersion parameters

- package-lock.json
- package.json
- src/ems_client.js
- test/ems_client_util.js
Follow up to https://github.com/elastic/kibana/pull/61846. Another step to unblocking https://github.com/elastic/kibana/pull/60942. This PR accomplishes the following:
- Removes `node-fetch`
- Adds warning if no `fetchFunction` provided
- Updates the patch version and adds notes around reason for patch
Feel free to suggest any revisions you think are necessary!
> Remove node-fetch dependency

- src/ems_client.js
- test/ems_client.test.js
This fixes a bug where URLs for tile and file manifests may be deformed when the `fileApiUrl` or `tileApiUrl` contain trailing slashes.
Also added a test to check for this in the future. 😅 
This is required to implement https://github.com/elastic/ems-landing-page/issues/168.
> Correctly format manifest URLs when api URLs contain trailing slashes

- src/ems_client.js
- test/ems_client.test.js
Backports the following commits to 7.7:
- Correctly format manifest URLs when api URLs contain trailing slashes (#21)
> [7.7] Correctly format manifest URLs when api URLs contain trailing slashes (#21)

- src/ems_client.js
- test/ems_client.test.js
Backports the following commits to 7.8:
- Correctly format manifest URLs when api URLs contain trailing slashes (#21)
> [7.8] Correctly format manifest URLs when api URLs contain trailing slashes (#21)

- src/ems_client.js
- test/ems_client.test.js
Backports the following commits to 7.6:
- Correctly format manifest URLs when api URLs contain trailing slashes (#21)
> [7.6] Correctly format manifest URLs when api URLs contain trailing slashes (#21)

- CHANGELOG.md
- package.json
- src/ems_client.ts
This PR will update to EMS v7.9 and get ready to publish 7.9.0 to NPM.
Fixes #29
> Bump to 7.9.0

- CHANGELOG.md
- package.json
- src/ems_client.ts
> [7.x] bump to 7.9.0 (#31)

- CHANGELOG.md
- package.json
- src/tms_service.ts
- test/ems_client.test.ts
- Fix regression for missing source type (#33)
> [7.x] Fix regression for missing source type (#33)

- src/file_layer.ts
- src/index.ts
- test/ems_client.test.ts
We need to expose the FileLayer and TMSService types for Kibana.
This also exposes a `getFields` method for FileLayer.
> Export FileLayer and TMSService

- package.json
- src/tms_service.ts
- yarn.lock
This PR replaces the @types/mapbox-gl library with our own typing for the EMS API. This avoids type-check issues in dependents as seen in [this issue](https://github.com/elastic/kibana/pull/68444).
> Remove @types/mapbox-gl 

- package.json
- src/tms_service.ts
- yarn.lock
- Remove @types/mapbox-gl  (#39)
> [7.x] Remove @types/mapbox-gl  (#39)

- package.json
- src/tms_service.ts
- yarn.lock
Backports the following commits to 7.9:
- Remove @types/mapbox-gl  (#39)
> [7.9] Remove @types/mapbox-gl  (#39)

- src/ems_service.ts
- src/tms_service.ts
- test/ems_client.test.ts
Removes the `getHtmlAttribution` method. Rather, clients should use the `getAttributions` method.
This has been updated in Kibana (https://github.com/elastic/kibana/pull/70888). A similar change needs to occur for the ems-landing-page (https://github.com/elastic/ems-landing-page/pull/228).
> Remove html-generation method

- src/ems_service.ts
- src/tms_service.ts
- test/ems_client.test.ts
- Remove html-generation method (#46)
> [7.x] Remove html-generation method (#46)

- src/ems_service.ts
- src/tms_service.ts
- test/ems_client.test.ts
Backports the following commits to 7.9:
- Remove html-generation method (#46)
> [7.9] Remove html-generation method (#46)

- src/ems_client.ts
- src/file_layer.ts
- test/ems_client.test.ts
- test/ems_mocks/sample_files.json
- test/ems_mocks/sample_files_proxied.json
The EMS file service supports multiple geospatial formats for file services. This PR introduces several new functions for retrieving a specific format for a layer. If the requested format is unavailable it falls back to the default format.
This PR is required for https://github.com/elastic/ems-landing-page/issues/255.
See also https://github.com/elastic/ems-file-service/issues/191
> Add functions to get specific file formats

- package.json
- src/ems_client.ts
- src/file_layer.ts
- test/__snapshots__/ems_client.test.ts.snap
- test/ems_client.test.ts
- test/ems_client_util.ts
- test/ems_mocks/sample_geojson.json
- test/ems_mocks/sample_topojson.json
- yarn.lock
Fixes #60. The `getVectorDataOfType` function takes either a `geojson` or `topojson` argument and retrieves and caches the specified vector file from EMS.
This is similar to how the vector tile stylesheets are cached. For file layers we use the `memoize` function rather than the `once` function because the argument may differ between function calls.
Note: Reviewers may want to hide whitespace changes.
> Add function to retrieve and cache vector files

- CHANGELOG.md
- LICENSE.txt
- NOTICE.txt
- package.json
- src/ems_client.ts
- src/ems_service.ts
- src/file_layer.ts
- src/index.ts
- src/origin.ts
- src/tms_service.ts
- src/utils.ts
- test/ems_client.test.ts
- test/ems_client_util.ts
Fixes #63 
`@elastic/ems-client` is an NPM library used by Elastic products for accessing [Elastic Maps Service](https://www.elastic.co/elastic-maps-service) APIs. The [Elastic Maps Service Terms of Service ](https://www.elastic.co/elastic-maps-service-terms)limit use of Elastic Maps Service to only unmodified Kibana binaries distributed by Elastic. So there should be no usage of the `@elastic/ems-client` library outside of Elastic products. 
Starting with 7.14.0, the `@elastic/ems-client` library will be licensed under the [Elastic License v2 (ELv2)](https://www.elastic.co/licensing/elastic-license). ELv2 is is a very simple, non-copyleft license, allowing for the right to "use, copy, distribute, make available, and prepare derivative works of the software” and has only three high-level …
> License change from Apache 2.0 to Elastic License v2

- CHANGELOG.md
- package.json
- src/ems_client.ts
- src/file_layer.ts
- src/tms_service.ts
- test/ems_client_util.ts
- yarn.lock
* Bump EMS version to 7.15
* Bump package.json version to 7.15.0
* Update CHANGELOG
* Fix linting issues
* Upgrade dependencies with `yarn upgrade`
Reviewers may find it easier to hide whitespace changes caused by lint fix.
> Bump to 7.15.0

- .backportrc.json
Update backport config file to include all branches, setting `8.0` as checked by default.
> Update backport config

- .ci/jobs/elastic+ems-client+pull-request.yml
CI is not reporting back when running the jobs for Pull Requests, this change should reconnect the reporting with the PR.
> [ci] Add status context to PR job definition

- package.json
- src/tms_service.ts
- yarn.lock
[Upgrading Kibana to maplibre 2.1.9](https://github.com/elastic/kibana/pull/127501) is blocked because ems-client exposes maplibre types and 1.5.2 types are not compatible with 2.1.9 types. This PR updates maplibre to 2.1.9 to unblock Kibana upgrade.
> update to maplibre 2.1.9

- src/tms_service.ts
- test/ems_client.test.ts
- test/ems_mocks/sample_style_bright_vector_source.json
This allows the user to optionally specify either `raster` or `vector` when using `getMinZoom` and `getMaxZoom` methods. If not specified, the `vector` format is used.
Previously, these methods only looked at the raster tile manifest which may have different zoom levels than the vector tiles. Since vector tiles are default in downstream clients, I think we should use the vector tiles manifest by default.
> Add optional `format` argument to getMinZoom getMaxZoom methods

- src/index.ts
Fixes #110
Exports the `blendMode` type for users of the `TMSService.transformColorProperties` method.
> Export blendMode type

- src/utils.ts
- test/ems_client_colour.test.ts
The result of `transformColor` was incorrect for colors defined as objects with `stops`. This PR fixes the output and includes a test.
> Fix transforming color definitions with stops

- src/tms_service.ts
- test/ems_client_colour.test.ts
Fixes #116 by accepting `undefined` color that will just return the properties with the original input color from the style definition.
> Support color to be undefined

- .ci/jobs/defaults.yml
- package.json
- yarn.lock
Replaces individual PRs from dependabot and snyk:
- Bump semver-regex from 3.1.3 to 3.1.4 #124
- fix: upgrade semver from 7.3.5 to 7.3.8 #128
- fix: upgrade @types/geojson from 7946.0.8 to 7946.0.10 #129
- fix: upgrade @types/topojson-client from 3.1.0 to 3.1.1 #130
Additionally:
- Dependencies upgraded from yarn upgrade-interactive
- Update CI jobs to run with node 16 and without the npm spin option
> Update dependencies and CI

- .ci/jobs/defaults.yml
- package.json
- yarn.lock
This will backport the following commits from `master` to `8.3`:
- [Update dependencies and CI (#131)](https://github.com/elastic/ems-client/pull/131)
> [8.3] Update dependencies and CI (#131)

- yarn.lock
This will backport the following commits from `master` to `8.3`:
- [Bump json5 from 2.2.0 to 2.2.3 (#134)](https://github.com/elastic/ems-client/pull/134)
- [Bump decode-uri-component from 0.2.0 to 0.2.2 (#133)](https://github.com/elastic/ems-client/pull/133)
> [8.3] Bump json5 from 2.2.0 to 2.2.3 (#134) | Bump decode-uri-component from 0.2.0 to 0.2.2 (#133)

- yarn.lock
Before tagging master for 8.4, bumping the library last upgrades
> Bumps babel/core, babel/cli, types/lodash and prettier

- yarn.lock
This will backport the following commits from `master` to `8.3`:
- [Bumps babel/core, babel/cli, types/lodash and prettier (#138)](https://github.com/elastic/ems-client/pull/138)
> [8.3] Bumps babel/core, babel/cli, types/lodash and prettier (#138)

- yarn.lock
- [Bumps babel/core, babel/cli, types/lodash and prettier (#138)](https://github.com/elastic/ems-client/pull/138)
> [7.17] Bumps babel/core, babel/cli, types/lodash and prettier (#138)

- CHANGELOG.md
- src/ems_client.ts
Updates the `CHANGELOG` and the `DEFAULT_EMS_VERSION` variable to put the library ready for release.
> Release 8.4.0

- .backportrc.json
- CHANGELOG.md
- package.json
- src/ems_client.ts
Bumps the library to 8.5.0 to host new features for future Elastic Stack releases.
> Bump to 8.5.0

- .buildkite/pipeline.yml
- .buildkite/pull-requests.json
This PR adds the pipeline to run the tests suite and build the library.
~Initially is using the default CI image but I've started a PR to our CI team to get a custom Docker image that will include the `yarn` command so we don't need to install it on every build. We will refine that in a follow-up PR.~
The pipeline uses a custom agent Docker image that includes support for running `yarn` and `gcloud`.
The Pull Requests configuration should give us the ability to trigger builds from comments, but also skip them if the `skip-ci` label is added, or if the changed files are not relevant (markdown files and CI settings).
> [Buildkite] Setting up CI to test the library on Pull Requests

- catalog-info.yaml
Follow up from #152 
- Include the pipeline definition in the catalog metadata file
- Allow only read for users outside EMS
- Document this library as a `Component` in Backstage ([example](https://github.com/elastic/rally/blob/master/catalog-info.yaml) for reference)
> Update the pipeline definition and document the library

- catalog-info.yaml
The schema is not validating this setting but I think that's an issue in the schema definition.
> Adds the env var to enable comments on PRs

- yarn.lock
Updates `semver` and:
* `prettier`
* `node-fetch`
* `babel/`
* `core`
* `cli`
* `preset-env`
* `present-typescript`
> Update semver and some development dependencies

- yarn.lock
- [Update semver and a few devDeps: prettier, node-fetch, babel[core|cli|preset-env|present-typescript] (#165)](https://github.com/elastic/ems-client/pull/165)
> [8.4] Update semver and a few devDeps: prettier, node-fetch, babel[core|cli|preset-env|present-typescript] (#165)

- .backportrc.json
- [Update backport config for backporting to 8.4 and 7.17 branches (#169)](https://github.com/elastic/ems-client/pull/169)
> [7.17] Update backport config for backporting to 8.4 and 7.17 branches (#169)

- package.json
- yarn.lock
- [Upgrade semver (#173)](https://github.com/elastic/ems-client/pull/173)
> [8.4] Upgrade semver (#173)

- package.json
- yarn.lock
- [Upgrade semver (#173)](https://github.com/elastic/ems-client/pull/173)
> [7.17] Upgrade semver (#173)

- yarn.lock
- [Upgrade babel components and types for lodash and node-fetch (#176)](https://github.com/elastic/ems-client/pull/176)
> [7.17] Upgrade babel components and types for lodash and node-fetch (#176)

- yarn.lock
- [Upgrade babel components and types for lodash and node-fetch (#176)](https://github.com/elastic/ems-client/pull/176)
> [8.4] Upgrade babel components and types for lodash and node-fetch (#176)

- yarn.lock
- [Bump tough-cookie from 4.0.0 to 4.1.3 (#181)](https://github.com/elastic/ems-client/pull/181)
> [8.4] Bump tough-cookie from 4.0.0 to 4.1.3 (#181)

- yarn.lock
- [Bump word-wrap from 1.2.3 to 1.2.4 (#184)](https://github.com/elastic/ems-client/pull/184)
> [7.17] Bump word-wrap from 1.2.3 to 1.2.4 (#184)

- yarn.lock
- [Bump word-wrap from 1.2.3 to 1.2.4 (#184)](https://github.com/elastic/ems-client/pull/184)
> [8.4] Bump word-wrap from 1.2.3 to 1.2.4 (#184)

- .buildkite/pipeline.yml
- .nvmrc
- package.json
Makes the support for Node 18 explicit by:
* Adding the `engines` section to the `package.json` file to make explicit that the library works between 16 and 18
* Adding a `.nvmrc` file for the `lts/hydrogen` release series
* Updates Buildkite job definition to use the Node 18 base image for EMS projects
> Upgrade to Node 18

- package.json
- yarn.lock
- [fix: upgrade semver from 7.5.2 to 7.5.4 (#191)](https://github.com/elastic/ems-client/pull/191)
> [8.4] fix: upgrade semver from 7.5.2 to 7.5.4 (#191)

- package.json
- yarn.lock
- [fix: upgrade semver from 7.5.2 to 7.5.4 (#191)](https://github.com/elastic/ems-client/pull/191)
> [7.17] fix: upgrade semver from 7.5.2 to 7.5.4 (#191)

- src/ems_client.ts
- src/index.ts
- test/ems_client.test.ts
Fixes #182
Part of  elastic/kibana#157094
Updates the processing of the versions passed when instantiating the client to understand `YYYY-MM-DD` version schema and update the endpoint URLS accordingly to use the `/latest` permanent link.
Removes the `DEFAULT_EMS_VERSION` constant since the client is not anymore attached to the cadence of the Elastic stack releases, and it is not expected for the EMS Client to have a default version for the services that are consumed.  
Also, following practice in the Kibana codebase limits the usage of `semver` functionality to the functions exposed at `semver/functions`.
> Update the client to understand serverless versioning

- CHANGELOG.md
- package.json
Bumping after tagging and releasing `8.5.0`.
Upgrading to a patch given there are no big changes here planned. We can always cut a `8.5` branch later if we want a minor release. This also saves maintenance overhead with backports, fixing dependencies and vulnerabilities in multiple branches and so on. 
Happy to discuss this, of course, if we feel better cutting `8.5` now.
> Bump to 8.5.1

- .github/CODEOWNERS
**Problem:**
For now, the docs team has to manually sync changes to this repo's OpenAPI spec files to the docs repo used to generate API reference docs.
**Solution:**
Add the Platform docs team as CODEOWNERS to ensure we're notified of any changes (and can then sync them).
**About the error...**
GitHub is complaining that the file contains errors. It doesn't — the Platform docs team exists ([proof](https://github.com/orgs/elastic/teams/platform-docs)), and the members have write access (the _team_ may not).
> Add platform docs as codeowners for OpenAPI files

- yarn.lock
- [Bump @babel/traverse from 7.15.4 to 7.23.2 (#198)](https://github.com/elastic/ems-client/pull/198)
> [8.4] Bump @babel/traverse from 7.15.4 to 7.23.2 (#198)

- CHANGELOG.md
- src/ems_client.ts
As discussed [here](https://github.com/elastic/ems-landing-page/pull/680#discussion_r1364148687), a way to get the EMS Version used to initialize the client was needed for EMS Landing Page.
> Add getEmsVersion method

- yarn.lock
```
info Direct dependencies
├─ @babel/cli@7.23.0
├─ @babel/core@7.23.2
├─ @babel/preset-env@7.23.2
├─ @babel/preset-typescript@7.23.2
├─ @types/chroma-js@2.4.2
├─ @types/lodash@4.14.200
├─ @types/node-fetch@2.6.7
├─ @types/semver@7.5.3
├─ @types/topojson-client@3.1.3
├─ @types/topojson-specification@1.0.4
└─ node-fetch@2.7.0
```
> Update yarn.lock via upgrade-interactive

- yarn.lock
- [Update yarn.lock via upgrade-interactive (#205)](https://github.com/elastic/ems-client/pull/205)
> [8.4] Update yarn.lock via upgrade-interactive (#205)

- yarn.lock
- [Update yarn.lock via upgrade-interactive (#205)](https://github.com/elastic/ems-client/pull/205)
> [7.17] Update yarn.lock via upgrade-interactive (#205)

- .buildkite/pipeline.yml
- .nvmrc
- package.json
- [Upgrade to Node 20 (#208)](https://github.com/elastic/ems-client/pull/208)
> [8.4] Upgrade to Node 20 (#208)

- .buildkite/pipeline.yml
- .nvmrc
- package.json
- [Upgrade to Node 20 (#208)](https://github.com/elastic/ems-client/pull/208)
> [7.17] Upgrade to Node 20 (#208)

- CHANGELOG.md
No idea about the reasoning to skip `7.17.0` but since we already bumped to 7.17.1 in #137 I think it is OK to skip the `7.17.0` :shrug:
> Release 7.17.1

- package.json
- src/ems_client.ts
- yarn.lock
LRU Cache version later used in Kibana does not have the `.clear` method, hence reverting to the deprecated `.reset`.
Apart from that:
* Added `@types/lru-cache`
* minor upgrades to `eslint`, `globals`, `minimatch`, and `typescript`.
> Fix lru-cache clear method and minor upgrades

- CHANGELOG.md
- package.json
- yarn.lock
* Upgrade to latest versions eslint, babel, and many types.
* Pinned `@types/lodash` since the last `4.17.6` is throwing building errrors
> [7.17] Upgrade dependencies

- .buildkite/build.sh
- .buildkite/compare_dependencies.js
- .buildkite/pipeline.yml
- eslint.config.mjs
- package.json
- yarn.lock
To help keep dependencies in sync with Kibana, adding a new script to our CI that checks that every dependency in EMS Client satisfies the version in Kibana.
The script and CI build will fail if there's any dependency not satisfying the version for Kibana and will only report those that don't satisfy Kibana's `devDependencies` list in the `package.json`.
The [second build](https://buildkite.com/elastic/ems-client/builds/331) of this PR shows how `lodash` and `lru-cache` are not aligned with Kibana `main` and failed. After upgrading them in 334d00c the script now only reports packages not aligned in Kibana `devDependencies` list, which should be OK to ignore for this library.
>[!note]
> When backporting this PR additional work may be required
> to align with the `7.17` branch of Kibana.
> Add script to check alignment with Kibana dependencies, update Lodash, downgrade lru-cache

- .buildkite/build.sh
- .buildkite/compare_dependencies.js
- .buildkite/pipeline.yml
- package.json
- yarn.lock
- [Add script to check alignment with Kibana dependencies, update Lodash, downgrade lru-cache (#242)](https://github.com/elastic/ems-client/pull/242)
> [7.17] Add script to check alignment with Kibana dependencies, update Lodash, downgrade lru-cache (#242)

- package.json
- yarn.lock
- [chore(deps): update dependency typescript to v5.5.4 (#260)](https://github.com/elastic/ems-client/pull/260)
> [7.17] chore(deps): update dependency typescript to v5.5.4 (#260)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/node to v20.16.1 (#261)](https://github.com/elastic/ems-client/pull/261)
> [7.17] chore(deps): update dependency @types/node to v20.16.1 (#261)

- package.json
- yarn.lock
- [chore(deps): update dependency @babel/preset-env to v7.25.4 (#262)](https://github.com/elastic/ems-client/pull/262)
> [7.17] chore(deps): update dependency @babel/preset-env to v7.25.4 (#262)

- package.json
- yarn.lock
- [chore(deps): update dependency husky to v9.1.5 (#265)](https://github.com/elastic/ems-client/pull/265)
> [7.17] chore(deps): update dependency husky to v9.1.5 (#265)

- package.json
- yarn.lock
- [chore(deps): update dependency globals to v15.9.0 (#264)](https://github.com/elastic/ems-client/pull/264)
> [7.17] chore(deps): update dependency globals to v15.9.0 (#264)

- .buildkite/pipeline.yml
- [chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#297)](https://github.com/elastic/ems-client/pull/297)
> [7.17] chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#297)

- package.json
- yarn.lock
- [chore(deps): update dependency ts-jest to v29.2.5 (#294)](https://github.com/elastic/ems-client/pull/294)
> [7.17] chore(deps): update dependency ts-jest to v29.2.5 (#294)

- yarn.lock
- [Bump micromatch from 4.0.7 to 4.0.8 (#301)](https://github.com/elastic/ems-client/pull/301)
> [7.17] Bump micromatch from 4.0.7 to 4.0.8 (#301)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/node to v20.16.2 (#306)](https://github.com/elastic/ems-client/pull/306)
> [7.17] chore(deps): update dependency @types/node to v20.16.2 (#306)

- package.json
- yarn.lock
- [chore(deps): update dependency @babel/cli to v7.25.6 (#308)](https://github.com/elastic/ems-client/pull/308)
> [7.17] chore(deps): update dependency @babel/cli to v7.25.6 (#308)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/node to v20.16.3 (#310)](https://github.com/elastic/ems-client/pull/310)
> [7.17] chore(deps): update dependency @types/node to v20.16.3 (#310)

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.4.0 (#312)](https://github.com/elastic/ems-client/pull/312)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.4.0 (#312)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/node to v20.16.4 (#315)](https://github.com/elastic/ems-client/pull/315)
> [7.17] chore(deps): update dependency @types/node to v20.16.4 (#315)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/node to v20.16.5 (#317)](https://github.com/elastic/ems-client/pull/317)
> [7.17] chore(deps): update dependency @types/node to v20.16.5 (#317)

- package.json
- yarn.lock
- [chore(deps): update dependency typescript to v5.6.2 (#321)](https://github.com/elastic/ems-client/pull/321)
> [7.17] chore(deps): update dependency typescript to v5.6.2 (#321)

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.5.0 (#322)](https://github.com/elastic/ems-client/pull/322)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.5.0 (#322)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/jest to v29.5.13 (#325)](https://github.com/elastic/ems-client/pull/325)
> [7.17] chore(deps): update dependency @types/jest to v29.5.13 (#325)

- package.json
- yarn.lock
- [chore(deps): update dependency husky to v9.1.6 (#326)](https://github.com/elastic/ems-client/pull/326)
> [7.17] chore(deps): update dependency husky to v9.1.6 (#326)

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.6.0 (#330)](https://github.com/elastic/ems-client/pull/330)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.6.0 (#330)

- package.json
- yarn.lock
- [fix(deps): update dependency @types/topojson-client to v3.1.5 (#329)](https://github.com/elastic/ems-client/pull/329)
> [7.17] fix(deps): update dependency @types/topojson-client to v3.1.5 (#329)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/node to v20.16.9 (#337)](https://github.com/elastic/ems-client/pull/337)
> [7.17] chore(deps): update dependency @types/node to v20.16.9 (#337)

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.7.0 (#339)](https://github.com/elastic/ems-client/pull/339)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.7.0 (#339)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/lodash to v4.17.9 (#336)](https://github.com/elastic/ems-client/pull/336)
> [7.17] chore(deps): update dependency @types/lodash to v4.17.9 (#336)

- package.json
- yarn.lock
- [chore(deps): pin dependency @eslint/core to 0.6.0 (#344)](https://github.com/elastic/ems-client/pull/344)
> [7.17] chore(deps): pin dependency @eslint/core to 0.6.0 (#344)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/node to v20.16.10 (#345)](https://github.com/elastic/ems-client/pull/345)
> [7.17] chore(deps): update dependency @types/node to v20.16.10 (#345)

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.8.0 (#348)](https://github.com/elastic/ems-client/pull/348)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.8.0 (#348)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/lodash to v4.17.11 (#374)](https://github.com/elastic/ems-client/pull/374)
> [7.17] chore(deps): update dependency @types/lodash to v4.17.11 (#374)

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.10.0 (#373)](https://github.com/elastic/ems-client/pull/373)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.10.0 (#373)

- package.json
- yarn.lock
- [chore(deps): update dependency @types/lodash to v4.17.12 (#377)](https://github.com/elastic/ems-client/pull/377)
> [7.17] chore(deps): update dependency @types/lodash to v4.17.12 (#377)

- CHANGELOG.md
- package.json
- renovate.json
* Updates CHANGELOG for 8.5.4 release
* Removes unnecessary line breaks for consistency.
> 8.6.0 changelog and version bump

- package.json
- src/ems_client.ts
- test/ems_client_util.ts
- yarn.lock
- [Remove node-fetch imports (#519)](https://github.com/elastic/ems-client/pull/519)
> [7.17] Remove node-fetch imports (#519)

- package.json
- renovate.json
- yarn.lock
* Bumps `package.json` and `renovate.json` to  `8.6.2`
* Downgrades `chroma-js` to match Kibana version. The library upgraded to use ESM modules and that is clashing with Jest tests, so aligning with the version used by Charts and EUI libraries.
> Bump to 8.6.2 and downgrade chroma-js

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.18.2 (#528)](https://github.com/elastic/ems-client/pull/528)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.18.2 (#528)

- package.json
- src/ems_client.ts
- tsconfig.json
- yarn.lock
- [Upgrade to lru-cache 11.0.2 (#663)](https://github.com/elastic/ems-client/pull/663)
> [7.17] Upgrade to lru-cache 11.0.2 (#663) and 11.1.0

- package.json
- yarn.lock
- [chore(deps): update typescript-eslint monorepo to v8.31.1 (#728)](https://github.com/elastic/ems-client/pull/728)
> [7.17] chore(deps): update typescript-eslint monorepo to v8.31.1 (#728)
